CREATE USER mystitch IDENTIFIED BY mystitch DEFAULT TABLESPACE users; 
GRANT CONNECT TO mystitch;
GRANT RESOURCE TO mystitch; 

CREATE TABLE mystitch.ADDRESS 
(
    ADDRESS_ID NUMBER(20,0) NOT NULL,    
    ADDRESSLINE1 VARCHAR2(100 BYTE) DEFAULT NULL,
    ADDRESSLINE2 VARCHAR2(100 BYTE) DEFAULT NULL,
    ZIPCODE VARCHAR2(5 BYTE) DEFAULT NULL,    
    TELNUMBER VARCHAR2(20 BYTE) DEFAULT NULL,
    CITY VARCHAR2(20 BYTE) DEFAULT NULL,
    STATE VARCHAR2(20 BYTE) DEFAULT NULL,
    COUNTRY VARCHAR2(20 BYTE) DEFAULT NULL,
    ADDRESSTYPE VARCHAR2(20 BYTE) DEFAULT NULL,
    CUSTOMER_ID NUMBER(20,0) NOT NULL
);

	  
CREATE TABLE mystitch.CREDITCARD 
(  
    CREDITCARD_ID NUMBER(20,0) NOT NULL,    
    CREDITCARD_NUMBER VARCHAR2(100 BYTE) DEFAULT NULL,
    CARDTYPE VARCHAR2(100 BYTE) DEFAULT NULL,
    EXPIRY TIMESTAMP DEFAULT NULL,    
    CCV NUMBER(5,0) NOT NULL,
    CUSTOMER_ID NUMBER(20,0) NOT NULL
);
	
CREATE TABLE mystitch.CUSTOMER 
(
    CUSTOMER_ID NUMBER(20,0) NOT NULL,
    TITLE VARCHAR2(50 BYTE) DEFAULT NULL,    
    FIRSTNAME VARCHAR2(100 BYTE) DEFAULT NULL,
    LASTNAME VARCHAR2(100 BYTE) DEFAULT NULL,
    EMAIL VARCHAR2(100 BYTE) DEFAULT NULL,    
    DOB TIMESTAMP DEFAULT NULL    
);	
	
CREATE TABLE mystitch.PRODUCT_ORDER 
(
    ORDER_ID NUMBER(20,0) NOT NULL, 
    TOTAL_PRICE NUMBER(20,0) NOT NULL,
    ORDER_NUMBER VARCHAR2(100 BYTE) NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL, 
    SHIPPING_CHARGE NUMBER(20,0) NULL,       
    ORDER_STATUS VARCHAR2(20 BYTE) DEFAULT 'NEW' NOT NULL,
    CUSTOMER_ID NUMBER(20,0) NOT NULL   
);		
	

CREATE TABLE mystitch.PRODUCT_ITEM
(
    ITEM_ID NUMBER(20,0) NOT NULL,    
    CATEGORY VARCHAR2(50 BYTE) NOT NULL,
    PRODUCT_CODE VARCHAR2(50 BYTE) NULL,
    PRODUCT_SIZE NUMBER(5,0) NULL,     
    COLOR VARCHAR2(30 BYTE) NULL,       
    BRAND VARCHAR2(50 BYTE) NULL, 
    NAME VARCHAR2(50 BYTE) NULL,
    PRICE NUMBER(20,0) NOT NULL
        
);

CREATE TABLE mystitch.ORDER_ITEM
(
    ORDER_ITEM_ID NUMBER(20,0) NOT NULL,
    ITEM_ID NUMBER(20,0) NOT NULL,
    QUANTITY NUMBER(20,0) NOT NULL,    
    ORDER_ID NUMBER(20,0) NOT NULL   
);			

CREATE TABLE mystitch.PRICE
(
    PRICE_ID NUMBER(20,0) NOT NULL,    
    CATEGORY VARCHAR2(50 BYTE) NOT NULL,
    SEASONAL_DISCOUNT NUMBER(20,0) NOT NULL,    
    PROMO_DISCOUNT NUMBER(20,0) NOT NULL,
    PRICE_AMOUNT NUMBER(20,0) NOT NULL
);	
	
ALTER TABLE mystitch.ADDRESS add CONSTRAINT ADDRESS_pk PRIMARY KEY (ADDRESS_ID);
ALTER TABLE mystitch.CREDITCARD add CONSTRAINT CREDITCARD_pk PRIMARY KEY (CREDITCARD_ID);
ALTER TABLE mystitch.CUSTOMER add CONSTRAINT CUSTOMER_pk PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE mystitch.PRODUCT_ORDER add CONSTRAINT PRODUCT_ORDER_pk PRIMARY KEY (ORDER_ID);
ALTER TABLE mystitch.PRODUCT_ITEM add CONSTRAINT PRODUCT_ITEM_pk PRIMARY KEY (ITEM_ID);
ALTER TABLE mystitch.ORDER_ITEM add CONSTRAINT ORDER_ITEM_pk PRIMARY KEY (ORDER_ITEM_ID);
ALTER TABLE mystitch.PRICE add CONSTRAINT PRICE_pk PRIMARY KEY (PRICE_ID);

ALTER TABLE mystitch.ADDRESS  ADD CONSTRAINT ADDRESS_fk1 FOREIGN KEY (CUSTOMER_ID) REFERENCES mystitch.CUSTOMER;
ALTER TABLE mystitch.CREDITCARD  ADD CONSTRAINT CREDITCARD_fk1 FOREIGN KEY (CUSTOMER_ID) REFERENCES mystitch.CUSTOMER;
ALTER TABLE mystitch.PRODUCT_ORDER  ADD CONSTRAINT PRODUCT_ORDER_fk1 FOREIGN KEY (CUSTOMER_ID) REFERENCES mystitch.CUSTOMER;
ALTER TABLE mystitch.ORDER_ITEM  ADD CONSTRAINT ORDER_ITEM_fk1 FOREIGN KEY (ITEM_ID) REFERENCES mystitch.PRODUCT_ITEM;
ALTER TABLE mystitch.ORDER_ITEM  ADD CONSTRAINT ORDER_ITEM_fk2 FOREIGN KEY (ORDER_ID) REFERENCES mystitch.PRODUCT_ORDER;

	
	
CREATE SEQUENCE CUSTOMER_SEQ INCREMENT BY 1 MINVALUE 1 NOCACHE;
CREATE SEQUENCE CREDITCARD_SEQ INCREMENT BY 1 START WITH 20 MINVALUE 1 NOCACHE;
CREATE SEQUENCE ADDRESS_SEQ INCREMENT BY 1 START WITH 20 MINVALUE 1 NOCACHE;
CREATE SEQUENCE PRODUCT_ORDER_SEQ INCREMENT BY 1 START WITH 20 MINVALUE 1 NOCACHE;
CREATE SEQUENCE PRODUCT_ITEM_SEQ INCREMENT BY 1 START WITH 20 MINVALUE 1 NOCACHE;
CREATE SEQUENCE ORDER_ITEM_SEQ INCREMENT BY 1 START WITH 20 MINVALUE 1 NOCACHE;
CREATE SEQUENCE PRICE_SEQ INCREMENT BY 1 START WITH 20 MINVALUE 1 NOCACHE;

 ITEM_ID NUMBER(20,0) NOT NULL,    
    CATEGORY VARCHAR2(50 BYTE) NOT NULL,
    PRODUCT_SIZE NUMBER(5,0) NULL,     
    COLOR VARCHAR2(30 BYTE) NULL,       
    BRAND VARCHAR2(50 BYTE) NULL, 
    NAME VARCHAR2(50 BYTE) NULL,
    PRODUCT_CODE VARCHAR2(50 BYTE) NULL    

---- populate ---
insert into mystitch.CUSTOMER(CUSTOMER_ID,TITLE,FIRSTNAME,LASTNAME,EMAIL,DOB) values(CUSTOMER_SEQ.nextval,'MR','JAMIE','NEDVED','jamie.nedved@mystitch.com.au',CURRENT_TIMESTAMP);

insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT1',32,'Black','Billabong',57,'BLT1');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT2',34,'Black','Levis',50,'BLT2');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT3',32,'Black','Levis',39,'BLT3');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT4',32,'Brown','Billabong',65,'BLT4');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT5',34,'Black','Billabong',50,'BLT5');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT6',36,'Brown','Lee',55,'BLT6');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT7',36,'Black','Hurley',70,'BLT7');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT8',34,'Brown','Nixon',40,'BLT8');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT9',36,'White','Hurley',35,'BLT9');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT10',34,'Choc','QuickSilver',80,'BLT10');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT11',32,'Black','Rusty',29,'BLT11');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT12',32,'Brown','Wrangler',34,'BLT12');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT13',32,'Black','Levis',60,'BLT13');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT14',32,'Brown','Billabong',84,'BLT14');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT15',34,'Black','Billabong',49,'BLT15');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT16',36,'Brown','Lee',45,'BLT16');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT17',36,'Black','Hurley',52,'BLT17');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT18',34,'Brown','Nixon',50,'BLT18');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT19',36,'White','Hurley',38,'BLT19');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT20',34,'Choc','QuickSilver',82,'BLT20');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT21',32,'Black','Rusty',57,'BLT21');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT22',32,'Brown','Wrangler',44,'BLT22');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT23',32,'Black','Levis',30,'BLT23');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT24',32,'Brown','Billabong',28,'BLT24');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT25',34,'Black','Billabong',65,'BLT25');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT26',36,'Brown','Lee',47,'BLT26');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT27',36,'Black','Hurley',50,'BLT27');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT28',34,'Brown','Nixon',40,'BLT28');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT29',36,'White','Hurley',42,'BLT29');
insert into mystitch.PRODUCT_ITEM(ITEM_ID,CATEGORY,PRODUCT_CODE,PRODUCT_SIZE,COLOR,BRAND,PRICE,NAME) values(PRODUCT_ITEM_SEQ.nextval,'MENS','BLT30',34,'Choc','QuickSilver',55,'BLT30');
		
			
	
		  
	  
	  
	  
	  
	  
	  